FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY BrankasServer.java .
COPY index.html .
COPY style.css .

RUN javac --add-modules jdk.httpserver BrankasServer.java

EXPOSE 80

CMD ["java", "--add-modules", "jdk.httpserver", "BrankasServer"]
